on:
  workflow_dispatch:
  
jobs:
  my_job:
    name: upload SARIF
    runs-on: ubuntu-18.04
    steps:
        - name: Checkout
          uses: actions/checkout@v3.3.0
          
        - name: Add SCW Training
          uses: SecureCodeWarrior/github-action-add-sarif-contextual-training@master
          with:
            inputSarifFile: ./SampleSarif1.sarif
            outputSarifFile: ./processed.sarif
            githubToken: ${{ secrets.GITHUB_TOKEN }}

        - name: Import Results
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: ./processed.sarif
