on:
  workflow_dispatch:
  
jobs:
  my_job:
    name: upload SARIF
    runs-on: ubuntu-18.04
    steps:
        - name: Checkout
          uses: actions/checkout@v3.3.0

        - name: Import Results
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: ./SampleSarif1.sarif
